name: ci

on:
  push:
    branches:
      - main

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./tests/testing_services/
          file: ./tests/testing_services/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uptime-testing-image:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/uptime-testing-image:latest
          cache-to: type=inline

  run-tests:
    runs-on: ubuntu-latest
    needs: build_image
    env:
      TELEGRAM_BOT: ${{ secrets.TELEGRAM_BOT }}
    services:
      testing-service:
        image: dunielm02/uptime-testing-image:latest
        ports:
          - "3030:22"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Install Dependecies
        run: |
          go mod download

      - name: Testing
        run: go test -race ./...